nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  webpack@*:
    dependencies:
      webpack-cli: "*"
  elm-webpack-loader@*:
    dependencies:
      temp: "*"
